project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://m-cespa.github.io/myblog/ # you must change this appropriately for RSS feeds to work properly
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/m-cespa
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



